# Generated by Django 4.0.5 on 2022-06-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('create_on', models.DateField()),
            ],
        ),
    ]
