# Generated by Django 4.0.5 on 2022-06-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateStudents',
            new_name='CreateStudent',
        ),
    ]
