# Generated by Django 4.0.5 on 2022-06-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_rename_createstudents_createstudent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateStudent',
            new_name='Student',
        ),
    ]
