# Generated by Django 4.0.5 on 2022-06-11 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_rename_createstudent_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='tbl_student',
        ),
    ]
