# Generated by Django 4.0.5 on 2022-06-11 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_rename_student_tbl_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_student',
            old_name='create_on',
            new_name='created_on',
        ),
    ]
