# Generated by Django 4.0.5 on 2022-06-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_rename_create_on_tbl_student_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_student',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
